# SwiftLint Configuration for RAKAZ iOS App

# Disabled Rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity

# Opt-In Rules
opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Excluded Paths
excluded:
  - Pods
  - build
  - DerivedData
  - .build
  - CapApp-SPM
  - public
  - Base.lproj

# Included Paths
included:
  - App

# File Length
file_length:
  warning: 500
  error: 1200

# Line Length
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Function Body Length
function_body_length:
  warning: 80
  error: 150

# Type Body Length
type_body_length:
  warning: 300
  error: 500

# Identifier Name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - i
    - j
    - x
    - y

# Nesting
nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Reporter
reporter: "xcode"

# Custom Rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\("
    message: "Use proper logging instead of print()"
    severity: warning
  
  no_force_cast:
    name: "No Force Cast"
    regex: "as!"
    message: "Avoid using force cast (as!), use conditional casting (as?) instead"
    severity: warning
